apiVersion: apps/v1
kind: Deployment
metadata:
  name: g01461345-swe645-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simple-html-app
  template:
    metadata:
      labels:
        app: simple-html-app
    spec:
      containers:
      - name: nginx-container
        image: localhost:5000/g01461345-swe645-assignment-02
        ports:
        - containerPort: 80
