apiVersion: v1
kind: Service
metadata:
  name: g01461345-swe645-service
spec:
  type: NodePort
  selector:
    app: simple-html-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30007
